### PR TITLE
Added my project to coding club| meisara1ta

### PR DESCRIPTION
**Pull request by meisara1ta**

### CODE REVIEW

**Comment by coder-zs-cse** [comment]
Hello @meisara1ta  congrats on completing your portfolio for this challenge. There is one small change needed before we merge your pull request. You have changed the Readme of the entire challenge repo. Please restore the contents of that readme and put your readme separately inside the directory of your project.

**Comment by meisara1ta** [comment]
I done the changes that you suggested. please now check it and let me know
if any more changes are required .

**Comment by coder-zs-cse** [comment]
Please delete the readme which is outside your directory

**Comment by meisara1ta** [comment]
I removed code from both files( readme.md and README.md). is it ok or i should have to clear files name also?

**Comment by meisara1ta** [comment]
I removed code from both files( readme.md and README.md). is it ok or i
should have to clear files name also?

**Comment by coder-zs-cse** [comment]
Yeah please delete those readme files which are outside your directory, because they will otherwise overwrite the challenge readme

**Comment by coder-zs-cse** [comment]
We are still waiting for your changes. You have almost completed the challenge.

**Comment by meisara1ta** [comment]
Sorry for the late  , I did the required changes, if any more will required
please let me know

**Pull request merged**
